### ISSUE TITLE
Renaming inconsistencies

### ISSUE THREAD

**Issue by yochananmarqos** [clipto-pro/Desktop#44]
You renamed the application to Clipto, yet the filenames are still named Clipto.pro.

**Comment by atrashler** [comment]
ok. thanks!

**Comment by atrashler** [comment]
fixed in 2.4.4 (https://github.com/clipto-pro/Desktop/releases/tag/v2.4.4)

**Comment by yochananmarqos** [comment]
The desktop file, binary and images still have the old name.

**Comment by atrashler** [comment]
could you send a screenshot? I have checked it on macOS and Windows only. On both platforms it does not have suffix ‘pro’ after update

**Comment by yochananmarqos** [comment]
No, I mean the actual filenames; i.e., `clipto.pro.desktop`, `clip.to`, `clip.to.png`, etc. 

 I'm the maintainer of the [`clipto.pro-bin`](https://aur.archlinux.org/packages/clipto.pro-bin/) AUR package which unpacks the AppImage and installs the files to the system as a regular package.

**Comment by atrashler** [comment]
ok. lets re-open it:) It is true, inside of the app the identifier ‘clipto.pro’ is still exists.

**Comment by yochananmarqos** [comment]
Thanks, it's resolved in 2.4.6. I've added [`clipto-bin`](https://aur.archlinux.org/packages/clipto-bin/) to the AUR and submitted a request to merge `clipto.pro-bin` into it.
